### ISSUE TITLE
Headings have no space after '#'

### ISSUE THREAD

**Issue by joallard** [xdamman/mediumexporter#3]
On a regular text, converter will omit the required space after `#` and before heading content.

Example output:
```
###This is an h3
```

(Great utility by the way)

**Comment by xdamman** [comment]
How can I reproduce this?

**Comment by joallard** [comment]
Seriously?......

1. Create a document with "This is an h3" as an h3.
2. Export

**Comment by xdamman** [comment]
This tool is meant to export a post on medium.com. 
Happy to take a look at the bug if you can send me the url of the medium post that you are trying to export.

**Comment by joallard** [comment]
I'm sorry, I just can't deal with this
